# Generated by Django 2.2.3 on 2019-07-26 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_hirecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirecontact',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
