# Generated by Django 2.2.3 on 2019-07-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_hirecontact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirecontact',
            name='website',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
