# Generated by Django 2.2.3 on 2019-07-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20190726_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirecontact',
            name='completion_date',
            field=models.CharField(blank=True, choices=[('As soon as posible', 'As soon as posible'), ('In 7 days', 'In 7 days'), ('In 15 days', 'In 15 days'), ('In 30 days', 'In 30 days'), ('Not sure/To be determined/Talk you later', 'Not sure/To be determined/Talk you later')], default='Not sure/To be determined/Talk you later', max_length=32, null=True),
        ),
    ]
