# Generated by Django 2.2.3 on 2019-07-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('prog_class', models.CharField(blank=True, max_length=120, null=True)),
                ('prog_bar_class', models.CharField(blank=True, max_length=120, null=True)),
                ('prog_info', models.CharField(max_length=120)),
                ('area_valuemin', models.IntegerField(default='0')),
                ('area_valuemax', models.IntegerField(default='100')),
                ('prog_info_perc', models.IntegerField(default='15')),
                ('prog_skill_perc', models.IntegerField()),
                ('show_prog_skill', models.IntegerField(blank=True, null=True)),
                ('prog_skill_lavel', models.CharField(choices=[('Beginner', 'beginner'), ('Elementary', 'elementary'), ('Intermediate', 'intermediate'), ('Advanced', 'advanced')], default='Intermediate', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', '-prog_skill_perc', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nj Nafir', max_length=255)),
                ('name', models.CharField(default='Nj Nafir', max_length=120)),
                ('description', models.CharField(default='Full Stack Web Developer', max_length=120)),
                ('view_portfolio_text', models.CharField(default='View Portfolio', max_length=120)),
                ('hire_me_text', models.CharField(default='Hire Me', max_length=120)),
                ('about_intro_text', models.CharField(default="I'm Nattachiuj Jaman Nafir", max_length=255)),
                ('exper_sec_title', models.CharField(default='Working with:', max_length=120)),
                ('exper_comment', models.TextField(default="I'm expert for this Full Stack Web Development career")),
                ('about_more_text', models.CharField(default='About More', max_length=120)),
                ('store_more_text', models.CharField(default='Portfolio More', max_length=120)),
                ('store_d_more_text', models.CharField(default='Show More', max_length=120)),
                ('post_more_text', models.CharField(default='Blog More', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exper_skill', models.ManyToManyField(blank=True, to='nafir.Skill')),
            ],
        ),
    ]
