# Generated by Django 2.2.3 on 2019-09-10 07:23

from django.db import migrations, models
import nafir.models


class Migration(migrations.Migration):

    dependencies = [
        ('nafir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='favicon',
            field=models.ImageField(default='dumy', upload_to=nafir.models.favicon_upload_path),
            preserve_default=False,
        ),
    ]
