# Generated by Django 2.2.3 on 2019-09-10 07:36

import django.core.files.storage
from django.db import migrations, models
import nafir.models


class Migration(migrations.Migration):

    dependencies = [
        ('nafir', '0002_info_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='picture',
            field=models.ImageField(default='dumy', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Md_Nadir\\Envs\\njnafir\\src\\njNafir\\njNafir_staticfiles_dirs'), upload_to=nafir.models.profile_picture_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='favicon',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Md_Nadir\\Envs\\njnafir\\src\\njNafir\\njNafir_staticfiles_dirs'), upload_to=nafir.models.favicon_upload_path),
        ),
    ]
