# Generated by Django 2.2.3 on 2019-07-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_category',
            new_name='category',
        ),
    ]
