# Generated by Django 2.2.3 on 2019-09-28 20:41

import about.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20190910_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='prove_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Md_Nadir\\Envs\\njnafir\\src\\njNafir\\njNafir_staticfiles_dirs\\med_prot_file'), upload_to=about.models.award_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='education',
            name='certificate',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Md_Nadir\\Envs\\njnafir\\src\\njNafir\\njNafir_staticfiles_dirs\\med_prot_file'), upload_to=about.models.education_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='certificate',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Md_Nadir\\Envs\\njnafir\\src\\njNafir\\njNafir_staticfiles_dirs\\med_prot_file'), upload_to=about.models.qualification_certificate_upload_path),
        ),
    ]
