# Generated by Django 2.2.3 on 2019-09-10 10:04

import django.core.files.storage
from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprojectfile',
            name='files',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Md_Nadir\\Envs\\njnafir\\src\\njNafir\\njNafir_staticfiles_cdn\\med_prot_file'), upload_to=portfolio.models.store_project_file_path),
        ),
    ]
